In [1]:
import csv
import numpy as np
import pandas as pd
import scipy.spatial.distance

from sklearn.cluster import DBSCAN
from sklearn import metrics
from sklearn.datasets.samples_generator import make_blobs
from sklearn.preprocessing import StandardScaler

from sklearn.cluster import AgglomerativeClustering
from sklearn.metrics import pairwise_distances
from sklearn.cluster import KMeans

import matplotlib.pyplot as plt


In [2]:
train_df = pd.read_csv('training_data.csv')

In [23]:
y_pred = KMeans(n_clusters=9, random_state=9).fit_predict(train_df)

In [24]:
#print (train_df)
kdf = pd.DataFrame(y_pred)
print (kdf[0].value_counts())

0    3541
5    2855
3    2628
7    2400
2    2100
1    1988
6    1526
8    1375
4     446
Name: 0, dtype: int64


In [14]:
model = DBSCAN(eps=0.03, min_samples=10, metric="hamming").fit(train_df)

print (model.labels_)

df = pd.DataFrame(model.labels_)
print (df[0].value_counts())

[ 0 -1  1 ... -1 -1  1]
-1      7128
 5      1365
 44      951
 1       583
 76      566
 58      501
 9       387
 32      371
 0       334
 11      306
 25      293
 64      289
 96      257
 33      238
 8       232
 74      163
 24      162
 55      160
 90      157
 56      154
 31      126
 69      121
 100     115
 68      115
 36      112
 53      111
 6        97
 103      97
 48       93
 45       89
        ... 
 81       14
 128      14
 22       14
 77       14
 101      14
 86       14
 61       14
 92       13
 132      13
 62       12
 54       12
 107      12
 106      12
 79       11
 131      11
 71       11
 134      11
 70       11
 34       11
 119      10
 114      10
 49       10
 136      10
 39       10
 89       10
 137      10
 122      10
 123      10
 108      10
 125      10
Name: 0, Length: 139, dtype: int64


In [20]:
model2 = DBSCAN(eps=0.042, min_samples=10, metric="hamming").fit(train_df)

print (model2.labels_)

df2 = pd.DataFrame(model2.labels_)
print (df2[0].value_counts())

[ 0 25  0 ... -1 -1  0]
-1      4038
 3      2899
 0      1484
 45     1138
 67      750
 27      704
 5       617
 28      607
 6       579
 60      324
 83      280
 23      256
 20      253
 48      233
 4       220
 65      218
 8       198
 15      189
 37      183
 41      153
 86      150
 68      134
 51      131
 16      131
 30      117
 46      115
 21      113
 64      102
 89       83
 66       81
        ... 
 95       19
 55       19
 71       19
 69       18
 72       18
 107      17
 87       17
 85       16
 40       16
 62       16
 108      15
 70       15
 38       15
 54       14
 90       14
 80       14
 33       13
 31       12
 63       12
 93       12
 97       11
 58       11
 7        10
 105      10
 77       10
 99       10
 92       10
 104      10
 106      10
 35       10
Name: 0, Length: 112, dtype: int64


In [21]:
df2.to_csv("dbcategoryeps0042sample10.csv")

In [22]:
model3 = DBSCAN(eps=0.045, min_samples=10, metric="hamming").fit(train_df)

print (model3.labels_)

df3 = pd.DataFrame(model3.labels_)
print (df3[0].value_counts())

df3.to_csv("dbcategoryeps0045sample10.csv")

[ 0 26  0 ... -1 -1  0]
-1     3571
 3     3541
 41    2256
 0     1540
 6     1393
 28     710
 5      631
 20     305
 67     282
 15     271
 23     265
 4      225
 8      206
 36     194
 2      178
 45     174
 39     159
 70     150
 18     138
 55     136
 29     118
 21     117
 53     104
 54      84
 73      83
 32      82
 33      79
 24      73
 22      68
 25      65
       ... 
 69      21
 63      21
 48      21
 17      21
 72      21
 56      20
 27      19
 57      19
 79      19
 14      19
 51      17
 38      16
 30      16
 31      15
 64      14
 78      13
 52      13
 62      12
 47      12
 61      11
 34      11
 81      11
 83      11
 74      10
 7       10
 89      10
 86      10
 13      10
 76      10
 87      10
Name: 0, Length: 92, dtype: int64


In [16]:
model1 = DBSCAN(eps=0.05, min_samples=20, metric="hamming").fit(train_df)

print (model1.labels_)

df1 = pd.DataFrame(model1.labels_)
print (df1[0].value_counts())

[ 0 15  0 ... 11 -1  0]
 5     4074
-1     3970
 2     3835
 0     1651
 18     730
 4      642
 14     416
 10     401
 12     314
 3      233
 11     213
 24     192
 1      179
 21     166
 27     159
 39     152
 33     140
 9      126
 17     121
 13     114
 32     101
 19      82
 37      64
 38      61
 15      55
 8       52
 26      50
 25      49
 40      47
 29      46
 34      44
 7       44
 35      41
 22      40
 31      33
 6       30
 20      29
 41      27
 28      27
 36      25
 42      24
 30      23
 16      22
 23      15
Name: 0, dtype: int64


In [17]:
df1.to_csv("smalldbcategory.csv")

In [6]:
model = DBSCAN(eps=0.066, min_samples=50, metric="hamming").fit(train_df)

print (model.labels_)


[ 0  0  0 ...  0 -1  0]


In [7]:
df = pd.DataFrame(model.labels_)
df.to_csv("some.csv")

In [11]:
n_clusters = 9
#labels = ['lab 1', 'lab 2', 'lab 3', 'lab 4', 'lab 5', 'lab 6', 'lab 7', 'lab 8']
aggmodel = AgglomerativeClustering(n_clusters=n_clusters, linkage="average", affinity="hamming")

aggmodel.fit(train_df)
print (aggmodel.labels_)


[2 2 2 ... 2 2 2]


In [12]:
ndf = pd.DataFrame(aggmodel.labels_)
ndf.to_csv("AgglomerativeClustering.csv")

In [3]:

train_df = pd.read_csv("ingr1125nf.csv")

MemoryError: 

In [ ]:
model3 = DBSCAN(eps=0.2, min_samples=10, metric="hamming").fit(train_df)

print (model3.labels_)

df3 = pd.DataFrame(model3.labels_)
print (df3[0].value_counts()) 

df3.to_csv("dbcategoryeps0045sample10.csv")